In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd


In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/weatherAUS.csv')
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


In [ ]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [ ]:
Y = Y.reshape(-1,1)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [ ]:
print(X)


[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]


In [ ]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])

In [ ]:
print(X)


[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]


In [ ]:
print(Y)


[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [ ]:
Y = np.array(Y,dtype=float)
print(Y)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)


print(X)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)


print(X_train)


[[ 0.22535368  1.03946939  0.07140543 ...  0.68369032  0.08145488
  -0.52979545]
 [ 1.42012717 -0.45263203  0.11369237 ... -0.41722163  0.22733303
  -0.52979545]
 [ 0.50647685 -0.20133073 -0.14002932 ... -0.06058818 -0.02065982
   1.88752093]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]


In [ ]:
print(Y_train)

[[1.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)

<ipython-input-18-84bb09ba651d>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_train,Y_train)


RandomForestClassifier(random_state=0)

In [ ]:
classifier.score(X_train,Y_train)

0.9999312525780283

In [ ]:
y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))


In [ ]:
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:155: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(y_pred)


['No' 'No' 'No' ... 'No' 'No' 'No']


In [ ]:
print(Y_test)


['Yes' 'Yes' 'No' ... 'Yes' 'No' 'No']


In [ ]:
y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [ ]:
df = np.concatenate((Y_test,y_pred),axis=1)


In [ ]:
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])

In [ ]:
print(dataframe)


      Rain on Tommorrow Predition of Rain
0                   Yes                No
1                   Yes                No
2                    No                No
3                    No               Yes
4                    No                No
...                 ...               ...
29087                No               Yes
29088                No                No
29089               Yes                No
29090                No                No
29091                No                No

[29092 rows x 2 columns]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8521930427608965

In [ ]:
dataframe.to_csv('prediction.csv')

In [ ]:
import pickle


In [ ]:
pickle.dump(classifier, open('//content/drive/MyDrive/model_saved','wb' ))

In [ ]:
pip install flask-ngrok

In [ ]:
from flask_ngrok import run_with_ngrok
from flask import Flask, request, render_template

In [ ]:
from flask import Flask,render_template,url_for,request,jsonify
from flask_cors import cross_origin
import pandas as pd
import numpy as np
import datetime
import pickle

app = Flask(__name__, template_folder="template")
model = pickle.load(open("/content/drive/MyDrive/model_saved", "rb"))

@app.route("/predict",methods=['GET', 'POST'])
@cross_origin()
def predict():
	return render_template("Predictor.html")
	if request.method == "POST":
		# DATE
		date = request.form['date']
		day = float(pd.to_datetime(date, format="%Y-%m-%dT").day)
		month = float(pd.to_datetime(date, format="%Y-%m-%dT").month)
		# MinTemp
		minTemp = float(request.form['mintemp'])
		# MaxTemp
		maxTemp = float(request.form['maxtemp'])
		# Rainfall
		rainfall = float(request.form['rainfall'])
		# Evaporation
		evaporation = float(request.form['evaporation'])
		# Sunshine
		sunshine = float(request.form['sunshine'])
		# Wind Gust Speed
		windGustSpeed = float(request.form['windgustspeed'])
		# Wind Speed 9am
		windSpeed9am = float(request.form['windspeed9am'])
		# Wind Speed 3pm
		windSpeed3pm = float(request.form['windspeed3pm'])
		# Humidity 9am
		humidity9am = float(request.form['humidity9am'])
		# Humidity 3pm
		humidity3pm = float(request.form['humidity3pm'])
		# Pressure 9am
		pressure9am = float(request.form['pressure9am'])
		# Pressure 3pm
		pressure3pm = float(request.form['pressure3pm'])
		# Temperature 9am
		temp9am = float(request.form['temp9am'])
		# Temperature 3pm
		temp3pm = float(request.form['temp3pm'])
		# Cloud 9am
		cloud9am = float(request.form['cloud9am'])
		# Cloud 3pm
		cloud3pm = float(request.form['cloud3pm'])
		# Cloud 3pm
		location = float(request.form['location'])
		# Wind Dir 9am
		winddDir9am = float(request.form['winddir9am'])
		# Wind Dir 3pm
		winddDir3pm = float(request.form['winddir3pm'])
		# Wind Gust Dir
		windGustDir = float(request.form['windgustdir'])
		# Rain Today
		rainToday = float(request.form['raintoday'])

		input_lst = [location , minTemp , maxTemp , rainfall , evaporation , sunshine ,
					 windGustDir , windGustSpeed , winddDir9am , winddDir3pm , windSpeed9am , windSpeed3pm ,
					 humidity9am , humidity3pm , pressure9am , pressure3pm , cloud9am , cloud3pm , temp9am , temp3pm ,
					 rainToday , month , day]
		pred = model.predict(input_lst)
		output = pred
		if output == 0:
			return render_template("after_sunny.html")
		else:
			return render_template("after_rainy.html")
	return render_template("predictor.html")

if __name__=='__main__':
	app.run(debug=True)

ModuleNotFoundError: ignored

In [ ]:
@app.route("/",methods=['GET'])
@cross_origin()
def home():

In [ ]:
!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/predictor.css">
    <title>Rain Prediction</title>
</head>
<body>

    <section id="prediction-form">
        <form class="form" action="/predict", method="POST">
            <h1 class="my-3 text-center"><b> PREDICTOR</b></h1>
            <div class="row">
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="date" class="date">Date</label>
                        <input type="date" class="form-control" id="date" name="date">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="mintemp" class="mintemp"> Minimum temprature</label>
                        <input type="text" class="form-control" id="mintemp" name="mintemp">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="maxtemp" class="maxtemp">Maximum Temperature</label>
                        <input type="text" class="form-control" id="maxtemp" name="maxtemp">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="rainfall" class="rainfall">Rainfall</label>
                        <input type="text" class="form-control" id="rainfall" name="rainfall">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="evaporation" class="evaporation">Evaporation</label>
                        <input type="text" class="form-control" id="evaporation" name="evaporation">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="sunshine" class="sunshine">Sunshine</label>
                        <input type="text" class="form-control" id="sunshine" name="sunshine">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="windgustspeed" class="windgustspeed">Wind Gust Speed</label>
                        <input type="text" class="form-control" id="windgustspeed" name="windgustspeed">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="windspeed9am" class="windspeed9am">Wind Speed 9am</label>
                        <input type="text" class="form-control" id="windspeed9am" name="windspeed9am">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="windspeed3pm" class="windspeed3pm">Wind Speed 3pm</label>
                        <input type="text" class="form-control" id="windspeed3pm" name="windspeed3pm">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="humidity9am" class="humidity9am">Humidity 9am</label>
                        <input type="text" class="form-control" id="humidity9am" name="humidity9am">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="humidity3pm" class="humidity3pm">Humidity 3pm</label>
                        <input type="text" class="form-control" id="humidity3pm" name="humidity3pm">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="pressure9am" class="pressure9am">Pressure 9am</label>
                        <input type="text" class="form-control" id="pressure9am" name="pressure9am">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="pressure3pm" class="pressure3pm">Pressure 3pm</label>
                        <input type="text" class="form-control" id="pressure3pm" name="pressure3pm">
                    </div>
                </div>

                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="temp9am" class="temp9am">Temperature 9am</label>
                        <input type="text" class="form-control" id="temp9am" name="temp9am">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="temp3pm" class=temp3pm">Temperature 3pm</label>
                        <input type="text" class="form-control" id="temp3pm" name="temp3pm">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="cloud9am" class="cloud9am">Cloud 9am</label>
                        <input type="text" class="form-control" id="cloud9am" name="cloud9am">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="cloud3pm" class="cloud3pm">Cloud 3pm</label>
                        <input type="text" class="form-control" id="cloud3pm" name="cloud3pm">
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="location" class="location" name="location">Location</label>
                        <select class="location" id="location" name="location" aria-label="Location">
                            <option selected>Select Location</option>
                            <option value= 24>Adelaide</option>
                            <option value= 7>Albany</option>
                            <option value= 30>Albury</option>
                            <option value= 46>AliceSprings</option>
                            <option value= 33>BadgerysCreek</option>
                            <option value= 14>Ballarat</option>
                            <option value= 36>Bendigo</option>
                            <option value= 21>Brisbane</option>
                            <option value= 2>Cairns</option>
                            <option value= 43>Cobar</option>
                            <option value= 9>CoffsHarbour</option>
                            <option value= 4>Dartmoor</option>
                            <option value= 11>Darwin</option>
                            <option value= 15>GoldCoast</option>
                            <option value= 17>Hobart</option>
                            <option value= 45>Katherine</option>
                            <option value= 23>Launceston</option>
                            <option value= 28>Melbourne</option>
                            <option value= 25>Melbourne Airport</option>
                            <option value= 44>Mildura</option>
                            <option value= 42>Moree</option>
                            <option value= 5>MountGambier</option>
                            <option value= 12>MountGinini</option>
                            <option value= 19>Newcastle	</option>
                            <option value= 47>Nhil</option>
                            <option value= 13>NorahHead</option>
                            <option value= 6>NorfolkIsland</option>
                            <option value= 32>Nuriootpa</option>
                            <option value= 40>PearceRAAF</option>
                            <option value= 31>Penrith</option>
                            <option value= 26>Perth</option>
                            <option value= 35>Perth Airport</option>
                            <option value= 1>Portland</option>
                            <option value= 37>Richmond</option>
                            <option value= 27>Sale</option>
                            <option value= 41>Salmon Gums</option>
                            <option value= 10>Sydney</option>
                            <option value= 16>Sydney Airport</option>
                            <option value= 39>Townsville</option>
                            <option value= 34>Tuggeranong</option>
                            <option value= 49>Uluru</option>
                            <option value= 38>WaggaWagga</option>
                            <option value= 3>Walpole</option>
                            <option value= 18>Watsonia</option>
                            <option value= 22>William Town</option>
                            <option value= 8>Witchcliffe</option>
                            <option value= 20>Wollongong</option>
                            <option value= 48>Woomera</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="winddir9am" class="winddir9am" name = "winddir9am">Wind Direction at 9am</label>
                        <select class="winddir9am" id="winddir9am" name="winddir9am" aria-label="Wind Direction 9am">
                            <option selected>Select Wind Direction at 9am</option>
                            <option value= 1>N</option>
                            <option value= 5>W</option>
                            <option value= 10>S</option>
                            <option value= 15>E</option>
                            <option value= 2>NW</option>
                            <option value= 9>NE</option>
                            <option value= 7>SW</option>
                            <option value= 13>SE</option>
                            <option value= 0>NNW</option>
                            <option value= 3>NNE</option>
                            <option value= 8>SSW</option>
                            <option value= 11>SSE</option>
                            <option value= 4>WNW</option>
                            <option value= 6>WSW</option>
                            <option value= 12>ENE</option>
                            <option value= 14>ESE</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="winddir3pm" class="winddir3pm" name = "winddir3pm">Wind Direction at 3pm</label>
                        <select class="winddir3pm" id="winddir3pm" name = "winddir3pm" aria-label="Wind Direction at 3pm">
                            <option selected>Select Wind Direction at 3pm</option>
                            <option value= 2>N</option>
                            <option value= 4>W</option>
                            <option value= 8>S</option>
                            <option value= 14>E</option>
                            <option value= 0>NW</option>
                            <option value= 11>NE</option>
                            <option value= 9>SW</option>
                            <option value= 10>SE</option>
                            <option value= 1>NNW</option>
                            <option value= 5>NNE</option>
                            <option value= 7>SSW</option>
                            <option value= 12>SSE</option>
                            <option value= 3>WNW</option>
                            <option value= 6>WSW</option>
                            <option value= 13>ENE</option>
                            <option value= 15>ESE</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="windgustdir" class="windgustdir" name = "windgustdir">Wind Gust Direction</label>
                        <select class="windgustdir" id="windgustdir" name = "windgustdir" aria-label="Wind Gust Direction">
                            <option selected>Select Wind Gust Direction</option>
                            <option value= 3>N</option>
                            <option value= 4>W</option>
                            <option value= 7>S</option>
                            <option value= 15>E</option>
                            <option value= 1>NW</option>
                            <option value= 11>NE</option>
                            <option value= 9>SW</option>
                            <option value= 12>SE</option>
                            <option value= 0>NNW</option>
                            <option value= 6>NNE</option>
                            <option value= 8>SSW</option>
                            <option value= 10>SSE</option>
                            <option value= 2>WNW</option>
                            <option value= 5>WSW</option>
                            <option value= 14>ENE</option>
                            <option value= 13>ESE</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6 my-2">
                    <div class="md-form">
                        <label for="raintoday" class="raintoday" name="raintoday">Rain Today</label>
                        <select class="raintoday" id="raintoday" name="raintoday" aria-label="Rain Today">
                            <option selected>Did it Rain Today</option>
                            <option value= 1>Yes</option>
                            <option value= 0>No</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6 my-2 d-flex align-items-end justify-content-around">
                    <button type="submit" class="btn btn-info button" style="margin-left: 100%;">Predict</button>
                </div>
            </div>
        </form>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>









In [ ]:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href='../static/after_rainy.css'>
    <title>Rainy Day</title>
</head>
<body>
    <h1 style="text-align: center; font-size: 3 rem; font-weight: bolder">RAINY DAY</h1>
    <div class="rainyimg">
        <img src="../static/rain.jpg"  style="height: 500px; width: 550px; margin-left: 32%">
    </div>
    <div>
        <h2><center> Tomorrow is going to be a rainy day, So enjoy yourselves
        with a cup of coffee and hot snack. </center></h2>
   </div>
</body>
</html>

In [ ]:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/sunny.css">
    <title>Sunny Day</title>
</head>
<body>
    <h1 style="text-align: center; font-size: 3 rem; font-weight: bolder">SUNNY DAY</h1>
    <div class="rainyimg">
        <img src="../static/suny.jpg" style="height: 500px; width: 550px; margin-left: 32%">
    </div>
    <div>
        <h2><center> Tomorrow is going to be a sunny day, So enjoy yourselves
        with a cool milkshake and icecream. </center></h2>
   </div>
</body>
</html>